name: Schedule Supabase Function

on:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minute

jobs:
  invoke-function:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Supabase Function
        run: |
          curl -L -X POST 'https://vawtxuuxksvpydqwphow.supabase.co/functions/v1/cron-task' -H 'Authorization: Bearer ${{secrets.SUPABASE_ANON_KEY}}' --data '{"name":"Functions"}'
